server:
  port: 8081

spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8081}
  boot:
    message : Hello Config Server from centralized config server git repo!!
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
jwt:
  secret:
    key: bxcxvcvxNsapkdvopasjvdpsakvd7GNnbgdsfgV5Dfvdsavdasjzvcxvcx90kFDS

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    org:
      springframework: ERROR
    root: INFO
    

