server:
  port: 8081

spring:
  boot:
    message: Hey Shubham!!
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shubhask/Ecommerce-config-server.git
          search-paths: config
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
jwt:
  secret:
    key: bxcxvcvxNsapkdvopasjvdpsakvd7GNnbgdsfgV5Dfvdsavdasjzvcxvcx90kFDS

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

