spring:
  application:
    name: auth-service
  boot
    message : Hello Shubham, What's up!
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8081}
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
logging:
  level:
    org:
      springframework: DEBUG
    root: info