server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    org:
      springframework: ERROR

spring:
  application:
    name: cart-management-service
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:3306/ecommerce_cart
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true