server:
  port: 0
logging:
  file:
    name: customer-service.log
  level:
    org:
      springframework: ERROR

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost}:3306/ecommerce_customer
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
